name: zip .gbr folder
on: 
  push:
    branches: master
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: zip GBR
        if: startsWith(github.ref, 'refs/tags/') 
        run: zip -r ESP32-breadboard-Adapter-${{ github.ref }}.gbr.zip ./ESP32-breadboard-Adapter.gbr
      - name: Create Release 
        if: startsWith(github.ref, 'refs/tags/') 
        uses: actions/create-release@v1 
        id: 
        create_release with: 
          draft: false 
          prerelease: false 
          release_name: ${{ github.ref }} 
          tag_name: ${{ github.ref }} 
          body_path: CHANGELOG.md 
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload Release 
        if: startsWith(github.ref, 'refs/tags/') 
        uses: actions/upload-release-asset@v1 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with: upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ESP32-breadboard-Adapter-${{ github.ref }}.gbr.zip
        asset_name: ESP32-breadboard-Adapter-${{ github.ref }}.gbr.zip
        asset_content_type: application/zip
